### ISSUE TITLE
Bing Output not defined

### ISSUE THREAD

**Issue by bubbabug** [GiusTex/EdgeGPT#2]
I am receiving an error on subsequent loads of the webui with the EdgeGPT extension enabled. It will work properly for the first time, but when I close the chat and try to start it again I receive the folowing error when attempting to generate any output (not just EdgeGPT output, but any query causes the error):

Traceback (most recent call last):
  File "C:\oobabooga_windows\installer_files\env\lib\site-packages\gradio\routes.py", line 395, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\oobabooga_windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 1193, in process_api
    result = await self.call_function(
  File "C:\oobabooga_windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 930, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\oobabooga_windows\installer_files\env\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\oobabooga_windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\oobabooga_windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\oobabooga_windows\installer_files\env\lib\site-packages\gradio\utils.py", line 491, in async_iteration
    return next(iterator)
  File "C:\oobabooga_windows\text-generation-webui\modules\chat.py", line 255, in regenerate_wrapper
    for history in chatbot_wrapper('', state, regenerate=True):
  File "C:\oobabooga_windows\text-generation-webui\modules\chat.py", line 174, in chatbot_wrapper
    prompt = apply_extensions('custom_generate_chat_prompt', text, state, **kwargs)
  File "C:\oobabooga_windows\text-generation-webui\modules\extensions.py", line 115, in apply_extensions
    return EXTENSION_MAP[typ](*args, **kwargs)
  File "C:\oobabooga_windows\text-generation-webui\modules\extensions.py", line 87, in _apply_custom_generate_chat_prompt
    return custom_generate_chat_prompt(text, state, **kwargs)
  File "C:\oobabooga_windows\text-generation-webui\extensions\EdgeGPT\script.py", line 138, in custom_generate_chat_prompt
    if(BingOutput!=None):
NameError: name 'BingOutput' is not defined

**Comment by bubbabug** [comment]
This only appears to happen when loading a new model. The workaround I have found is to remove the extension, load in any model, choose the model you want to use and reload with the extension, then remain on that model as long as you use the extension.

**Comment by GiusTex** [comment]
I updated the script, tell me if it works now

**Comment by bubbabug** [comment]
It appears to be working, as far as I can tell. I had the error pop up on me once last night and once today, but I can't seem to figure out how to replicate it reliably. With that said, I have tested as much as I can and it seems to be working fine with the new script. 

Thank you so much! I love the new logging options, they make it much easier to see how the bot integrates the Bing output, which helps me formulate my queries better.

**Comment by GiusTex** [comment]
Happy to hear that!
If you encounter again the bug you can open again this issue.
