### ISSUE TITLE
CaptchaChallenge: User needs to solve CAPTCHA to continue.

### ISSUE THREAD

**Issue by RandomInternetPreson** [GiusTex/EdgeGPT#20]
Hello :3 your extension works with the latest and greatest version of oobabooga! thank you <3

I was able to do a search, but subsequent searches yielded the authentication error, so I followed the cookie instructions and have the option enabled. 

But now I keep getting this error message:
CaptchaChallenge: User needs to solve CAPTCHA to continue.

Is there a site I can go to do to the CAPTCHA? 

This is the entire error message:
Traceback (most recent call last):
  File "F:\OobaboogaJuly5\oobabooga_windows\installer_files\env\lib\site-packages\gradio\routes.py", line 427, in run_predict
    output = await app.get_blocks().process_api(
  File "F:\OobaboogaJuly5\oobabooga_windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "F:\OobaboogaJuly5\oobabooga_windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 1067, in call_function
    prediction = await utils.async_iteration(iterator)
  File "F:\OobaboogaJuly5\oobabooga_windows\installer_files\env\lib\site-packages\gradio\utils.py", line 336, in async_iteration
    return await iterator.__anext__()
  File "F:\OobaboogaJuly5\oobabooga_windows\installer_files\env\lib\site-packages\gradio\utils.py", line 329, in __anext__
    return await anyio.to_thread.run_sync(
  File "F:\OobaboogaJuly5\oobabooga_windows\installer_files\env\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "F:\OobaboogaJuly5\oobabooga_windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "F:\OobaboogaJuly5\oobabooga_windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "F:\OobaboogaJuly5\oobabooga_windows\installer_files\env\lib\site-packages\gradio\utils.py", line 312, in run_sync_iterator_async
    return next(iterator)
  File "F:\OobaboogaJuly5\oobabooga_windows\text-generation-webui\modules\chat.py", line 304, in generate_chat_reply_wrapper
    for i, history in enumerate(generate_chat_reply(text, state, regenerate, _continue, loading_message=True)):
  File "F:\OobaboogaJuly5\oobabooga_windows\text-generation-webui\modules\chat.py", line 289, in generate_chat_reply
    for history in chatbot_wrapper(text, state, regenerate=regenerate, _continue=_continue, loading_message=loading_message):
  File "F:\OobaboogaJuly5\oobabooga_windows\text-generation-webui\modules\chat.py", line 205, in chatbot_wrapper
    prompt = apply_extensions('custom_generate_chat_prompt', text, state, **kwargs)
  File "F:\OobaboogaJuly5\oobabooga_windows\text-generation-webui\modules\extensions.py", line 199, in apply_extensions
    return EXTENSION_MAP[typ](*args, **kwargs)
  File "F:\OobaboogaJuly5\oobabooga_windows\text-generation-webui\modules\extensions.py", line 86, in _apply_custom_generate_chat_prompt
    return extension.custom_generate_chat_prompt(text, state, **kwargs)
  File "F:\OobaboogaJuly5\oobabooga_windows\text-generation-webui\extensions\EdgeGPT\script.py", line 238, in custom_generate_chat_prompt
    asyncio.run(EdgeGPT())
  File "F:\OobaboogaJuly5\oobabooga_windows\installer_files\env\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "F:\OobaboogaJuly5\oobabooga_windows\installer_files\env\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "F:\OobaboogaJuly5\oobabooga_windows\text-generation-webui\extensions\EdgeGPT\script.py", line 212, in EdgeGPT
    response = await bot.ask(prompt=UserInput, conversation_style=style, simplify_response=True)
  File "F:\OobaboogaJuly5\oobabooga_windows\installer_files\env\lib\site-packages\EdgeGPT\EdgeGPT.py", line 116, in ask
    async for final, response in self.chat_hub.ask_stream(
  File "F:\OobaboogaJuly5\oobabooga_windows\installer_files\env\lib\site-packages\EdgeGPT\chathub.py", line 197, in ask_stream
    raise Exception(
Exception: CaptchaChallenge: User needs to solve CAPTCHA to continue.

**Comment by GiusTex** [comment]
You can try writing something on `bing.com` to complete the captcha, and if you still get the error you can use the `cookies option` (after writing something on `bing.com`). There is also a photo of the captcha on the readme, under `known weaknesses`

**Comment by RandomInternetPreson** [comment]
Awesome thank you I will try this out this evening.  Thank you again for all of your hard work and good luck on your exams!

**Comment by GiusTex** [comment]
Thanks again :), I have 2 exams left, then I can enjoy the summer.
I hope the extension works, if it does tell me and close the issues 👍🏻

**Comment by RandomInternetPreson** [comment]
Woot! Yup things are working perfectly now.  I ended up needing to get the cookies while having the Bing chat window open.

I actually chatted with Bing for the first time...it was terrible lol

I'm amazed that my local LLMs are so much better than Bing?

Thanks again :3

**Comment by GiusTex** [comment]
Yes, it's not incredible, but for doing researches and summarizing them to me it's great, I use it only for that. For other things open source llms or gpt4 (through free sites like you.com-chat) are the way
