### ISSUE TITLE
Issue with Oobabooga

### ISSUE THREAD

**Issue by darkanubis0100** [GiusTex/EdgeGPT#22]
```
Traceback (most recent call last):
  File "C:\Users\Administrator\Documents\Dev\oobabooga_windows\installer_files\env\lib\site-packages\gradio\routes.py", line 427, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\Administrator\Documents\Dev\oobabooga_windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "C:\Users\Administrator\Documents\Dev\oobabooga_windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 1067, in call_function
    prediction = await utils.async_iteration(iterator)
  File "C:\Users\Administrator\Documents\Dev\oobabooga_windows\installer_files\env\lib\site-packages\gradio\utils.py", line 336, in async_iteration
    return await iterator.__anext__()
  File "C:\Users\Administrator\Documents\Dev\oobabooga_windows\installer_files\env\lib\site-packages\gradio\utils.py", line 329, in __anext__
    return await anyio.to_thread.run_sync(
  File "C:\Users\Administrator\Documents\Dev\oobabooga_windows\installer_files\env\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\Administrator\Documents\Dev\oobabooga_windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\Administrator\Documents\Dev\oobabooga_windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\Administrator\Documents\Dev\oobabooga_windows\installer_files\env\lib\site-packages\gradio\utils.py", line 312, in run_sync_iterator_async
    return next(iterator)
  File "C:\Users\Administrator\Documents\Dev\oobabooga_windows\text-generation-webui\modules\chat.py", line 304, in generate_chat_reply_wrapper
    for i, history in enumerate(generate_chat_reply(text, state, regenerate, _continue, loading_message=True)):
  File "C:\Users\Administrator\Documents\Dev\oobabooga_windows\text-generation-webui\modules\chat.py", line 289, in generate_chat_reply
    for history in chatbot_wrapper(text, state, regenerate=regenerate, _continue=_continue, loading_message=loading_message):
  File "C:\Users\Administrator\Documents\Dev\oobabooga_windows\text-generation-webui\modules\chat.py", line 205, in chatbot_wrapper
    prompt = apply_extensions('custom_generate_chat_prompt', text, state, **kwargs)
  File "C:\Users\Administrator\Documents\Dev\oobabooga_windows\text-generation-webui\modules\extensions.py", line 199, in apply_extensions
    return EXTENSION_MAP[typ](*args, **kwargs)
  File "C:\Users\Administrator\Documents\Dev\oobabooga_windows\text-generation-webui\modules\extensions.py", line 86, in _apply_custom_generate_chat_prompt
    return extension.custom_generate_chat_prompt(text, state, **kwargs)
  File "C:\Users\Administrator\Documents\Dev\oobabooga_windows\text-generation-webui\extensions\EdgeGPT\script.py", line 241, in custom_generate_chat_prompt    asyncio.run(EdgeGPT())
  File "C:\Users\Administrator\Documents\Dev\oobabooga_windows\installer_files\env\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\Documents\Dev\oobabooga_windows\installer_files\env\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\Administrator\Documents\Dev\oobabooga_windows\text-generation-webui\extensions\EdgeGPT\script.py", line 212, in EdgeGPT
    response = await bot.ask(prompt=UserInput, conversation_style=style, simplify_response=True)
UnboundLocalError: local variable 'style' referenced before assignment
```

That's what I see when I try to use EdgeGPT, it doesn't matter how I set it up, as soon as I start a chat (even with all the boxes empty), that error appears, it is the same error under any circumstances.

**Comment by GiusTex** [comment]
Are you using the latest version of the extension and the webui? If yes, it's strange, the style is set by default at the start of the script (so it's already assigned when referenced); I can't replicate the error, can you add a screen of the options/boxes?

**Comment by darkanubis0100** [comment]
> Are you using the latest version of the extension and the webui? If yes, it's strange, the style is set by default at the start of the script (so it's already assigned when referenced); I can't replicate the error, can you add a screen of the options/boxes? Can you also add at line 194? (It's a copy of line 45, to see if that line is not read by the script)`BingConversationStyle="creative"`

Yes, I'm using both in their latest version (updated 35 minutes ago) and I found it very strange.

And I will try to add that line

**Comment by GiusTex** [comment]
You should have something like this:
```
BingConversationStyle="creative" #line 45

def input_modifier(string): #line 62
#...

def custom_generate_chat_prompt(user_input, state, **kwargs): #line 127
#...

BingConversationStyle="creative" #test fix #line 194
if BingConversationStyle=="creative":
                style = ConversationStyle.creative

bot_created=False
            if (bot_created==False):
            #...

response = await bot.ask(prompt=UserInput, conversation_style=style, simplify_response=True) #line 212
#...
```
My options:
![image](https://github.com/GiusTex/EdgeGPT/assets/112352961/58e3f62c-9af1-45e7-9d00-c927b6723f7b)
![image](https://github.com/GiusTex/EdgeGPT/assets/112352961/af87d48c-f52b-4b64-a0ca-49f5c6ae4b0f)

**Comment by darkanubis0100** [comment]
@GiusTex I managed to fix it just by adding it in line 194. Now the problem is the captcha, I followed the steps to the letter but I can't get over the error "Exception: CaptchaChallenge: User needs to solve CAPTCHA to continue.

I'm a regular Bing user so I've already passed the captcha a long time ago, but it still doesn't work even if I pass my own cookies.

**Comment by GiusTex** [comment]
You need to write something on bing.com to trigger the captcha, and the cookies

**Comment by darkanubis0100** [comment]
> You need to write something on bing.com to trigger the captcha, and the cookies. If you get captcha error you have to do the captcha again: ![image](https://user-images.githubusercontent.com/112352961/252144808-1080f20f-6260-4468-bbc1-8cf017a68d6f.png)

Ah!

It was when using the chat, I thought it was with the search engine.

**Comment by GiusTex** [comment]
Yeah chat, good !

**Comment by GiusTex** [comment]
> I managed to fix it just by adding it in line 194

This is still a problem though, cause you can't change the conversation style from the webui interface
![image](https://github.com/GiusTex/EdgeGPT/assets/112352961/337f5bc4-7e5d-4590-b1cb-a3ea8e557de8)

**Comment by darkanubis0100** [comment]
> > I managed to fix it just by adding it in line 194
> 
> This is still a problem though, cause you can't change the conversation style from the webui interface ![image](https://user-images.githubusercontent.com/112352961/252144953-337f5bc4-7e5d-4590-b1cb-a3ea8e557de8.png)
> 
> #### Edit:
> Can you add here a copy of your `script.py` ? (change `py` to `txt`). Or if you want I can give you my copy of the script, to find where is the error

It's not a problem, thanks for the help <3

**Comment by GiusTex** [comment]
Ok, you're welcome! 👍🏻
