### ISSUE TITLE
Failed to load the extension EdgeGPT in oobabooga in Win 10

### ISSUE THREAD

**Issue by mrdc** [GiusTex/EdgeGPT#23]
Hello,

I have this error, when trying to use your fork as an extension in `oobabooga` in Windows 10. Win is weird for this stuff, but at the moment I have only Win for tests.

```
2023-07-19 10:20:20 INFO:Loading the extension "EdgeGPT"...
2023-07-19 10:20:20 ERROR:Failed to load the extension "EdgeGPT".
Traceback (most recent call last):
  File "f:\oobabooga_windows\text-generation-webui\modules\extensions.py", line 36, in load_extensions
    exec(f"import extensions.{name}.script")
  File "<string>", line 1, in <module>
  File "f:\oobabooga_windows\text-generation-webui\extensions\EdgeGPT\script.py", line 8, in <module>
    from EdgeGPT.EdgeGPT import Chatbot, ConversationStyle
ModuleNotFoundError: No module named 'EdgeGPT'
```
It uses `miniconda` under the hood and I've installed `EdgeGPT` in `conda` env (`pip3 install edgegpt`): 

```
 .\conda.exe list
# packages in environment at F:\oobabooga_windows\installer_files\conda:
#
# Name                    Version                   Build  Channel
...
edgegpt                   0.12.1                   pypi_0    pypi
...
```
EdgeGPT package is installed but somehow not accessed by the extension.
Have no clue why the extension fails for load.

**Comment by GiusTex** [comment]
Did you `windows_cmd.bat` to install EdgeGpt?
