### ISSUE TITLE
KeyError: 'adaptiveCards'

### ISSUE THREAD

**Issue by ThePrimeDev** [GiusTex/EdgeGPT#26]
I got no response using the extension, here is my log:

```
Traceback (most recent call last):
  File "C:\Users\Jerryyy\AI\oobabooga_windows\installer_files\env\lib\site-packages\gradio\routes.py", line 427, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\Jerryyy\AI\oobabooga_windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "C:\Users\Jerryyy\AI\oobabooga_windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 1067, in call_function
    prediction = await utils.async_iteration(iterator)
  File "C:\Users\Jerryyy\AI\oobabooga_windows\installer_files\env\lib\site-packages\gradio\utils.py", line 336, in async_iteration
    return await iterator.__anext__()
  File "C:\Users\Jerryyy\AI\oobabooga_windows\installer_files\env\lib\site-packages\gradio\utils.py", line 329, in __anext__
    return await anyio.to_thread.run_sync(
  File "C:\Users\Jerryyy\AI\oobabooga_windows\installer_files\env\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\Jerryyy\AI\oobabooga_windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\Jerryyy\AI\oobabooga_windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\Jerryyy\AI\oobabooga_windows\installer_files\env\lib\site-packages\gradio\utils.py", line 312, in run_sync_iterator_async
    return next(iterator)
  File "C:\Users\Jerryyy\AI\oobabooga_windows\text-generation-webui\modules\chat.py", line 305, in generate_chat_reply_wrapper
    for i, history in enumerate(generate_chat_reply(text, state, regenerate, _continue, loading_message=True)):
  File "C:\Users\Jerryyy\AI\oobabooga_windows\text-generation-webui\modules\chat.py", line 290, in generate_chat_reply
    for history in chatbot_wrapper(text, state, regenerate=regenerate, _continue=_continue, loading_message=loading_message):
  File "C:\Users\Jerryyy\AI\oobabooga_windows\text-generation-webui\modules\chat.py", line 206, in chatbot_wrapper
    prompt = apply_extensions('custom_generate_chat_prompt', text, state, **kwargs)
  File "C:\Users\Jerryyy\AI\oobabooga_windows\text-generation-webui\modules\extensions.py", line 208, in apply_extensions
    return EXTENSION_MAP[typ](*args, **kwargs)
  File "C:\Users\Jerryyy\AI\oobabooga_windows\text-generation-webui\modules\extensions.py", line 86, in _apply_custom_generate_chat_prompt
    return extension.custom_generate_chat_prompt(text, state, **kwargs)
  File "C:\Users\Jerryyy\AI\oobabooga_windows\text-generation-webui\extensions\edgegpt\script.py", line 238, in custom_generate_chat_prompt
    asyncio.run(EdgeGPT())
  File "C:\Users\Jerryyy\AI\oobabooga_windows\installer_files\env\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Jerryyy\AI\oobabooga_windows\installer_files\env\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\Jerryyy\AI\oobabooga_windows\text-generation-webui\extensions\edgegpt\script.py", line 212, in EdgeGPT
    response = await bot.ask(prompt=UserInput, conversation_style=style, simplify_response=True)
  File "C:\Users\Jerryyy\AI\oobabooga_windows\installer_files\env\lib\site-packages\EdgeGPT\EdgeGPT.py", line 116, in ask
    async for final, response in self.chat_hub.ask_stream(
  File "C:\Users\Jerryyy\AI\oobabooga_windows\installer_files\env\lib\site-packages\EdgeGPT\chathub.py", line 174, in ask_stream
    resp_txt = result_text + response["arguments"][0][
KeyError: 'adaptiveCards'
```

**Comment by GiusTex** [comment]
Are you using `--listen`? There was a [similar problem](https://github.com/GiusTex/EdgeGPT/issues/7#issuecomment-1565997140) before, and removing `--listen` helped a bit (the error showed up less frequently)

**Comment by GiusTex** [comment]
If you still have problems you can open again this issue

**Comment by akaikite** [comment]
I have the same problem. And this workaround doesn't solve it.

**Comment by GiusTex** [comment]
Can you update the webui with `windows_update.bat`, just in case this extension too, and tell me if there are still errors ?

**Comment by akaikite** [comment]
> Can you update the webui with `windows_update.bat`, just in case this extension too, and tell me if there are still errors ?

Very simple questions can now be answered (current time, exchange rate, etc...), but most questions end up with an error like <line 174, in ask_stream resp_text = result_text + response["arguments"][0][ KeyError: 'adaptiveCards'>.
