### ISSUE TITLE
error when trying "precise" style

### ISSUE THREAD

**Issue by yesbroc** [GiusTex/EdgeGPT#27]
```Hey Bing, solve 2x^2 - 5x + 3 = 0 step by step
Traceback (most recent call last):
  File "C:\Users\orijp\anaconda3\envs\textgen\lib\site-packages\gradio\routes.py", line 427, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\orijp\anaconda3\envs\textgen\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "C:\Users\orijp\anaconda3\envs\textgen\lib\site-packages\gradio\blocks.py", line 1067, in call_function
    prediction = await utils.async_iteration(iterator)
  File "C:\Users\orijp\anaconda3\envs\textgen\lib\site-packages\gradio\utils.py", line 336, in async_iteration
    return await iterator.__anext__()
  File "C:\Users\orijp\anaconda3\envs\textgen\lib\site-packages\gradio\utils.py", line 329, in __anext__
    return await anyio.to_thread.run_sync(
  File "C:\Users\orijp\anaconda3\envs\textgen\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\orijp\anaconda3\envs\textgen\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\orijp\anaconda3\envs\textgen\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\orijp\anaconda3\envs\textgen\lib\site-packages\gradio\utils.py", line 312, in run_sync_iterator_async
    return next(iterator)
  File "C:\Users\orijp\OneDrive\Desktop\chatgpts\oobabooga_windows\oobabooga_windows\text-generation-webui\modules\chat.py", line 305, in generate_chat_reply_wrapper
    for i, history in enumerate(generate_chat_reply(text, state, regenerate, _continue, loading_message=True)):
  File "C:\Users\orijp\OneDrive\Desktop\chatgpts\oobabooga_windows\oobabooga_windows\text-generation-webui\modules\chat.py", line 290, in generate_chat_reply
    for history in chatbot_wrapper(text, state, regenerate=regenerate, _continue=_continue, loading_message=loading_message):
  File "C:\Users\orijp\OneDrive\Desktop\chatgpts\oobabooga_windows\oobabooga_windows\text-generation-webui\modules\chat.py", line 206, in chatbot_wrapper
    prompt = apply_extensions('custom_generate_chat_prompt', text, state, **kwargs)
  File "C:\Users\orijp\OneDrive\Desktop\chatgpts\oobabooga_windows\oobabooga_windows\text-generation-webui\modules\extensions.py", line 208, in apply_extensions
    return EXTENSION_MAP[typ](*args, **kwargs)
  File "C:\Users\orijp\OneDrive\Desktop\chatgpts\oobabooga_windows\oobabooga_windows\text-generation-webui\modules\extensions.py", line 86, in _apply_custom_generate_chat_prompt
    return extension.custom_generate_chat_prompt(text, state, **kwargs)
  File "C:\Users\orijp\OneDrive\Desktop\chatgpts\oobabooga_windows\oobabooga_windows\text-generation-webui\extensions\EdgeGPT\script.py", line 238, in custom_generate_chat_prompt
    asyncio.run(EdgeGPT())
  File "C:\Users\orijp\anaconda3\envs\textgen\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\orijp\anaconda3\envs\textgen\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\orijp\OneDrive\Desktop\chatgpts\oobabooga_windows\oobabooga_windows\text-generation-webui\extensions\EdgeGPT\script.py", line 212, in EdgeGPT
    response = await bot.ask(prompt=UserInput, conversation_style=style, simplify_response=True)
UnboundLocalError: local variable 'style' referenced before assignment

```

**Comment by yesbroc** [comment]
> * Are you using the last version of the webui + extension?
> * Did you write just `precise` (without quotes) ?

yes and yes

**Comment by GiusTex** [comment]
What combination are you using? (with/without `activation word`, with/without `cookies`, ... I tried with-without `activation word` and always with `cookies` [without them it doesn't work for me today], and the extension works).
Try deleting and installing again the extension. If this doesn't work, install again the webui too, I downloaded them again today too and they work...

**Comment by yesbroc** [comment]
1, windows
2, with ativation word and cookies
will try the edgegpt reinstall fix

**Comment by GiusTex** [comment]
If you still have problems you can open again this issue
