### ISSUE TITLE
KeyError: 'conversationSignature'

### ISSUE THREAD

**Issue by Jake36921** [GiusTex/EdgeGPT#32]
### Describe the bug

doesn't retrieve any output from bing, always stuck at searching. Also stops any responses from the ai even after clearing the chat history or reloading the model

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

use the extension normally

### Logs

```shell
Traceback (most recent call last):
  File "E:\etc\oobabooga_windows\installer_files\env\lib\site-packages\gradio\routes.py", line 427, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\etc\oobabooga_windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "E:\etc\oobabooga_windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 1067, in call_function
    prediction = await utils.async_iteration(iterator)
  File "E:\etc\oobabooga_windows\installer_files\env\lib\site-packages\gradio\utils.py", line 336, in async_iteration
    return await iterator.__anext__()
  File "E:\etc\oobabooga_windows\installer_files\env\lib\site-packages\gradio\utils.py", line 329, in __anext__
    return await anyio.to_thread.run_sync(
  File "E:\etc\oobabooga_windows\installer_files\env\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "E:\etc\oobabooga_windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 2106, in run_sync_in_worker_thread
    return await future
  File "E:\etc\oobabooga_windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 833, in run
    result = context.run(func, *args)
  File "E:\etc\oobabooga_windows\installer_files\env\lib\site-packages\gradio\utils.py", line 312, in run_sync_iterator_async
    return next(iterator)
  File "E:\etc\oobabooga_windows\text-generation-webui\modules\chat.py", line 308, in generate_chat_reply_wrapper
    for i, history in enumerate(generate_chat_reply(text, state, regenerate, _continue, loading_message=True)):
  File "E:\etc\oobabooga_windows\text-generation-webui\modules\chat.py", line 293, in generate_chat_reply
    for history in chatbot_wrapper(text, state, regenerate=regenerate, _continue=_continue, loading_message=loading_message):
  File "E:\etc\oobabooga_windows\text-generation-webui\modules\chat.py", line 230, in chatbot_wrapper
    prompt = apply_extensions('custom_generate_chat_prompt', text, state, **kwargs)
  File "E:\etc\oobabooga_windows\text-generation-webui\modules\extensions.py", line 223, in apply_extensions
    return EXTENSION_MAP[typ](*args, **kwargs)
  File "E:\etc\oobabooga_windows\text-generation-webui\modules\extensions.py", line 99, in _apply_custom_generate_chat_prompt
    return extension.custom_generate_chat_prompt(text, state, **kwargs)
  File "E:\etc\oobabooga_windows\text-generation-webui\extensions\EdgeGPT\script.py", line 241, in custom_generate_chat_prompt
    asyncio.run(EdgeGPT())
  File "E:\etc\oobabooga_windows\installer_files\env\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "E:\etc\oobabooga_windows\installer_files\env\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "E:\etc\oobabooga_windows\text-generation-webui\extensions\EdgeGPT\script.py", line 207, in EdgeGPT
    bot = await Chatbot.create(cookies=cookies)
  File "E:\etc\oobabooga_windows\installer_files\env\lib\site-packages\EdgeGPT\EdgeGPT.py", line 41, in create
    self.chat_hub = ChatHub(
  File "E:\etc\oobabooga_windows\installer_files\env\lib\site-packages\EdgeGPT\chathub.py", line 42, in __init__
    conversation_signature=conversation.struct["conversationSignature"],
KeyError: 'conversationSignature'
```

### System Info

```shell
Cpu: 5600g
Gpu: 3060 12gb
ram: 16gb 3200mhz
Os: Windows 11 pro 22H2
```

**Comment by GiusTex** [comment]
Update the extension's code, then restart the webui or update its state (you can delete the chat; close the webui; reload the model, etc). Today Edgegpt worked again without cookies, while I got the error using them, so you can try not using them and see if it works.
