### ISSUE TITLE
Required to be logged in to MSFT?

### ISSUE THREAD

**Issue by dblacknc** [GiusTex/EdgeGPT#5]
I followed the instructions and created what looks like a legit cookies.json file.  However I'm not logged in on a Microsoft account and the error implies I need to.  Is that correct?

Traceback (most recent call last):
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/gradio/routes.py", line 393, in run_predict
    output = await app.get_blocks().process_api(
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/gradio/blocks.py", line 1108, in process_api
    result = await self.call_function(
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/gradio/blocks.py", line 929, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/gradio/utils.py", line 490, in async_iteration
    return next(iterator)
  File "/root/text-generation-webui/modules/chat.py", line 253, in cai_chatbot_wrapper
    for history in chatbot_wrapper(text, state):
  File "/root/text-generation-webui/modules/chat.py", line 180, in chatbot_wrapper
    prompt = apply_extensions('custom_generate_chat_prompt', text, state, **kwargs)
  File "/root/text-generation-webui/modules/extensions.py", line 132, in apply_extensions
    return EXTENSION_MAP[typ](*args, **kwargs)
  File "/root/text-generation-webui/modules/extensions.py", line 84, in _apply_custom_generate_chat_prompt
    return custom_generate_chat_prompt(text, state, **kwargs)
  File "/root/text-generation-webui/extensions/EdgeGPT/script.py", line 168, in custom_generate_chat_prompt
    asyncio.run(EdgeGPT())
  File "/root/miniconda3/envs/textgen/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/root/miniconda3/envs/textgen/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/root/text-generation-webui/extensions/EdgeGPT/script.py", line 156, in EdgeGPT
    bot = Chatbot(cookie_path='extensions/EdgeGPT/cookies.json')
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/EdgeGPT.py", line 595, in __init__
    _Conversation(self.cookies, self.proxy),
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/EdgeGPT.py", line 339, in __init__
    raise NotAllowedToAccess(self.struct["result"]["message"])
EdgeGPT.NotAllowedToAccess: Sorry, you need to login first to access this service.

**Comment by GiusTex** [comment]
Yes, you need to login first

**Comment by dblacknc** [comment]
OK thanks.  I was able to get it to work for one search then it failed on another.  I'll open a separate issue for that.
