### ISSUE TITLE
KeyError: 'messages'

### ISSUE THREAD

**Issue by dblacknc** [GiusTex/EdgeGPT#8]
After a couple successful searches, I entered:
"Bing what's the marine forecast this week for Titusville, Florida?"

It sat for a while and finally returned in the log (no UI output):

Traceback (most recent call last):
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/gradio/routes.py", line 393, in run_predict
    output = await app.get_blocks().process_api(
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/gradio/blocks.py", line 1108, in process_api
    result = await self.call_function(
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/gradio/blocks.py", line 929, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/gradio/utils.py", line 490, in async_iteration
    return next(iterator)
  File "/root/text-generation-webui/modules/chat.py", line 253, in cai_chatbot_wrapper
    for history in chatbot_wrapper(text, state):
  File "/root/text-generation-webui/modules/chat.py", line 180, in chatbot_wrapper
    prompt = apply_extensions('custom_generate_chat_prompt', text, state, **kwargs)
  File "/root/text-generation-webui/modules/extensions.py", line 132, in apply_extensions
    return EXTENSION_MAP[typ](*args, **kwargs)
  File "/root/text-generation-webui/modules/extensions.py", line 84, in _apply_custom_generate_chat_prompt
    return custom_generate_chat_prompt(text, state, **kwargs)
  File "/root/text-generation-webui/extensions/EdgeGPT/script.py", line 168, in custom_generate_chat_prompt
    asyncio.run(EdgeGPT())
  File "/root/miniconda3/envs/textgen/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/root/miniconda3/envs/textgen/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/root/text-generation-webui/extensions/EdgeGPT/script.py", line 157, in EdgeGPT
    response = await bot.ask(prompt=UserInput, conversation_style=ConversationStyle.creative)
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/EdgeGPT.py", line 633, in ask
    async for final, response in self.chat_hub.ask_stream(
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/EdgeGPT.py", line 547, in ask_stream
    response["item"]["messages"][-1]["contentOrigin"] == "Apology"
KeyError: 'messages'

**Comment by GiusTex** [comment]
- How did you install the webui ? (An old and working one-click installer, manually cloning the repo and installing dependencies with Conda, ecc...)
- Do you start the webui with some arguments? (From the old "start-webui.bat", or from the python script)
- Are you using other extensions, do they work, does EdgeGPT work without them?

I updated the webui (I'm using an old version built with a one-click installer), and it works for me, both with Hey Bing and with a custom word without restarting the webui, you must have something different from my setup, maybe in the questions above

**Comment by GiusTex** [comment]
I can't replicate this error, and I updated the extension too, tell me if you still get the error, in case one can open the issue again
