### ISSUE TITLE
Type Error: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by syddharth** [GiusTex/EdgeGPT#9]
User input:
 Hey Bing; what is the day today?
Traceback (most recent call last):
  File "C:\AI\T2T\oobabooga-windows\installer_files\env\lib\site-packages\gradio\routes.py", line 395, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\AI\T2T\oobabooga-windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 1193, in process_api
    result = await self.call_function(
  File "C:\AI\T2T\oobabooga-windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 930, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\AI\T2T\oobabooga-windows\installer_files\env\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\AI\T2T\oobabooga-windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\AI\T2T\oobabooga-windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\AI\T2T\oobabooga-windows\installer_files\env\lib\site-packages\gradio\utils.py", line 491, in async_iteration
    return next(iterator)
  File "C:\AI\T2T\oobabooga-windows\text-generation-webui\modules\chat.py", line 246, in cai_chatbot_wrapper
    for history in chatbot_wrapper(text, state):
  File "C:\AI\T2T\oobabooga-windows\text-generation-webui\modules\chat.py", line 173, in chatbot_wrapper
    prompt = apply_extensions('custom_generate_chat_prompt', text, state, **kwargs)
  File "C:\AI\T2T\oobabooga-windows\text-generation-webui\modules\extensions.py", line 140, in apply_extensions
    return EXTENSION_MAP[typ](*args, **kwargs)
  File "C:\AI\T2T\oobabooga-windows\text-generation-webui\modules\extensions.py", line 81, in _apply_custom_generate_chat_prompt
    return custom_generate_chat_prompt(text, state, **kwargs)
TypeError: 'NoneType' object is not callable

I followed the instructions to install EdgeGPT and copied the cookies as well, never got it to work.

**Comment by GiusTex** [comment]
The webui has been updated, I'm updating the script to work again

**Comment by GiusTex** [comment]
For now I can't find a clean solution, so you have to do this, sorry:
Download: [extensions.txt](https://github.com/GiusTex/EdgeGPT/files/11441372/extensions.txt), change it to `extensions.py` and replace text-generation-webui>module>extensions.py with the downloaded file, or change directly these lines (of extensions.py):
```
def _apply_custom_generate_chat_prompt(text, state, **kwargs):
    custom_generate_chat_prompt = None
    for extension, _ in iterator():
        if hasattr(extension, 'custom_generate_chat_prompt'):
            return custom_generate_chat_prompt(text, state, **kwargs)
    
    return None
```
with:
```
# custom_generate_chat_prompt handling - currently only the first one will work
#def _apply_custom_generate_chat_prompt(text, state, **kwargs):
   # custom_generate_chat_prompt = None
  #  for extension, _ in iterator():
     #   if hasattr(extension, 'custom_generate_chat_prompt'):
      #      return custom_generate_chat_prompt(text, state, **kwargs)
    
   # return None

def _apply_custom_generate_chat_prompt(text, state, **kwargs):
    custom_generate_chat_prompt_func = None
    for extension, _ in iterator():
        if hasattr(extension, 'custom_generate_chat_prompt'):
            custom_generate_chat_prompt_func = extension.custom_generate_chat_prompt
            break
            
    if callable(custom_generate_chat_prompt_func):
        return custom_generate_chat_prompt_func(text, state, **kwargs)
    else:
        return None
```
This way you'll have the old code, turned off by "#" and the new quick fix. There are other extensions that doesn't work, I hope oobabooga will fix the extensions file quickly
